import React from 'react';
import CodeBlockImpl from './CodeBlockImpl';

const PreToCodeBlock = (preProps: any) => {
  const props = preToCodeBlock(preProps);

  if (props) {
    return (
      <pre>
        <CodeBlockImpl {...props} />
      </pre>
    );
  } else {
    return <pre {...preProps} />;
  }
};

/**
 * We are doing this to support both <pre> and <code> tags generated by MDX
 *
 */
export function preToCodeBlock(preProps: any) {
  if (
    // children is code element
    preProps.children &&
    // code props
    preProps.children.props
  ) {
    const {
      noLine = false,
      fileName,
      noExt = false,
      noHeader = false,
      codePenID,
      add,
      del,
    } = preProps;
    const {className = '', ...props} = preProps.children.props;

    return {
      className,
      fileName,
      noExt,
      noHeader,
      codePenID,
      noLine,
      add,
      del,
      ...props,
    };
  }
}

export default PreToCodeBlock;
