/**
 * We are doing this to support both <pre> and <code> tags generated by MDX
 *
 */
export function preToCodeBlock(preProps: any) {
  if (
    // children is code element
    preProps.children &&
    // code props
    preProps.children.props
  ) {
    const {
      noLine = false,
      fileName,
      noExt = false,
      noHeader = false,
      codePenID,
    } = preProps;
    const {className = '', ...props} = preProps.children.props;

    return {
      className,
      fileName,
      noExt,
      noHeader,
      codePenID,
      noLine,
      ...props,
    };
  }
}
